COLUMN_MEANINGS = {
    "P1": "Delusions",
    "P2": "Conceptual disorganisation",
    "P3": "Hallucinatory behavior",
    "P4": "Excitement",
    "P5": "Grandiosity",
    "P6": "Suspiciousness/persecution",
    "P7": "Hostility",
    "N1": "Blunted affect",
    "N2": "Emotional withdrawal",
    "N3": "Poor rapport",
    "N4": "Passive/apathetic social withdrawal",
    "N5": "Difficulty in abstract thinking",
    "N6": "Lack of spontaneity & flow of conversation",
    "N7": "Stereotyped thinking",
    "G1": "Somatic concern",
    "G2": "Anxiety",
    "G3": "Guilt feelings",
    "G4": "Tension",
    "G5": "Mannerisms & posturing",
    "G6": "Depression",
    "G7": "Motor retardation",
    "G8": "Uncooperativeness",
    "G9": "Unusual thought content",
    "G10": "Disorientation",
    "G11": "Poor attention",
    "G12": "Lack of judgement & insight",
    "G13": "Disturbance of volition",
    "G14": "Poor impulse control",
    "G15": "Preoccupation",
    "G16": "Active social avoidance",
}

RATING_MEANINGS = {
    1: "absent",
    2: "minimal",
    3: "mild",
    4: "moderate",
    5: "moderate severe",
    6: "severe",
    7: "extreme",
}
